apiVersion: v1
kind: ResourceQuota
metadata:
  name: kafka-cpu-memory-quota
  namespace: kafka-dev
spec:
  hard:
    requests.cpu: '1'
    requests.memory: 2Gi
    limits.cpu: '2'
    limits.memory: 4Gi
  scopes:
    - NotTerminating